= Execute a migration from CLI using the RH OpenStack Vmware Migration Toolkit collection with Heat functionality

== Enable Heat Orchestration Service in the control plane

In the bastion, patch the openstack control plane CR:

[source,bash,role=execute]
----
oc patch openstackcontrolplane openstack-control-plane \
  -n openstack \
  --type='merge' \
  -p '{
    "spec": {
      "heat": {
        "enabled": true,
        "template": {
          "customServiceConfig": "[DEFAULT]\nenable_stack_adopt = true\n"
        }
      }
    }
  }'
----
. Sample Output
----
openstackcontrolplane.core.openstack.org/openstack-control-plane patched
----

Wait for the Heat services to be ready:

[source,bash,role=execute]
----
oc get Heat,HeatAPI,HeatEngine,HeatCFNAPI -n openstack
----

. Sample Output
----
NAME                           STATUS   MESSAGE
heat.heat.openstack.org/heat   True     Setup complete
----

== Configure os-migrate vmware migration kit

=== Configure the Ansible inventory

In the bastion, create the folder to store the ansible variables:

[source,bash,role=execute]
----
mkdir -p /home/lab-user/os-migrate-env
----

Then,create the ansible inventory:

[source,bash,role=execute,subs=attributes]
----
cat << EOF > /home/lab-user/os-migrate-env/inventory.yaml
migrator:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

conversion_host:
  hosts:
    {rhoso_conversion_host_ip}:
      ansible_ssh_user: cloud-user
      ansible_ssh_private_key_file: /runner/key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
EOF
----

=== Configure the Ansible inventory

In the bastion, create an alias to use the openstack command in the Red Hat OpenStack Services on OpenShift (RHOSO) deployment:

[source,bash,role=execute]
----
oc project openstack
alias openstack="oc exec -t openstackclient -- openstack"
----

Get the security group ID:

[source,bash,role=execute]
----
SECURITY_GROUP_ID=$(openstack security group list | awk '/ basic / {print $2}')
----

Create the os_migrate_vars.yamls file:

[source,bash,role=execute,subs=attributes]
----
cat << EOF > /home/lab-user/os-migrate-env/os_migrate_vars_demo_redhat_com.yaml
runner_from_aee: true
# osm working directory:
os_migrate_vmw_data_dir: /tmp/os-migrate
copy_openstack_credentials_to_conv_host: false

# Re-use an already deployed conversion host:
already_deploy_conversion_host: true

# If no mapped network then set the openstack network:
openstack_private_network: private

# Security groups for the instance:
security_groups: ${SECURITY_GROUP_ID}
use_existing_flavor: false

# network settings for openstack:
os_migrate_create_network_port: true
copy_metadata_to_conv_host: true
used_mapped_networks: false

# Use for settings rhel network device:
os_migrate_configure_network: true

use_heat: true

os_migrate_tear_down: false

vms_list:
  - haproxy-{guid}
EOF
----

[NOTE]

In the *vms_list* we specify the list of VMs to be migrated in this example, we will migrate the virtual machine haproxy-{guid}

Get the project ID and authurl from the tenant we are executing the conversion:

[source,bash,role=execute]
----
PROJECT_ID=$(openstack project list | grep ' admin ' | awk '{print $2}')
AUTH_URL=$(openstack endpoint list --service identity --interface public -c URL -f value)
----

And finally create the secrets files with :

[source,bash,role=execute,subs=attributes]
----
cat << EOF > /home/lab-user/os-migrate-env/secrets_demo_redhat_com.yaml
# VMware parameters:
vcenter_hostname: {vcenter_console}
vcenter_username: {vcenter_full_user}
vcenter_password: {vcenter_password}
vcenter_datacenter: RS01

os_cloud_environ: demo.redhat.com
dst_cloud:
  auth:
    auth_url: ${AUTH_URL}
    username: admin
    project_id: ${PROJECT_ID}
    project_name: admin
    user_domain_name: Default
    password: openstack
  region_name: regionOne
  interface: public
  insecure: true
  identity_api_version: 3
EOF
----

== Execute the virtual machine migration

In the bastion, launch the migration:

[source,bash,role=execute,subs=attributes]
----
sudo podman secret create conv-key /home/lab-user/.ssh/{guid}key.pem
sudo podman run --network host -it -v $PWD/os-migrate-env:/runner/env:z --env ANSIBLE_CALLBACKS_ENABLED=profile_tasks --secret conv-key,target=/runner/key,mode=0600,type=mount --user root localhost/rhospvmt-ee:latest ansible-playbook -i /runner/env/inventory.yaml os_migrate.vmware_migration_kit.migration -e @/runner/env/os_migrate_vars_demo_redhat_com.yaml -e @/runner/env/secrets_demo_redhat_com.yaml
----

Check that the VM has been migrated as stack:

[source,bash,role=execute,subs=attributes]
----
alias openstack="oc exec -t openstackclient -- openstack"
openstack stack list
----

. Sample Output

[source,bash,subs=attributes]
----
+--------------------------------------+-----------------------+----------------------------------+-----------------+----------------------+--------------+
| ID                                   | Stack Name            | Project                          | Stack Status    | Creation Time        | Updated Time |
+--------------------------------------+-----------------------+----------------------------------+-----------------+----------------------+--------------+
| 81aed5c8-5c0d-4439-a219-72502184f7f3 | os-migrate-1772123054 | 02dec38ba4e04cbdb98f643c8affcc6d | CREATE_COMPLETE | 2026-02-26T16:37:04Z | None         |
+--------------------------------------+-----------------------+----------------------------------+-----------------+----------------------+--------------+
----