apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=v0.1.1

resources:
  - openstack_control_plane.yaml
  - openstack-ipaddresspools.yaml
  - openstack-l2advertisement.yaml
  - openstack-net-attach-def.yaml
  - openstack_netconfig.yaml
  - openstack-nncp.yaml