---
# Ansible Galaxy requirements for RHOSO deployment playbooks

collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.general
    version: ">=6.0.0"
  - name: community.crypto
    version: ">=2.0.0"
